spring.application.name=backend-api

spring.datasource.url=jdbc:mysql://mysql-game-tracker-singleton.j.aivencloud.com:23481/defaultdb?ssl-mode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

gametracker.app.jwtSecret=VGhpc0lzQVNlY3VyZUFuZExvbmdFbm91Z2hCYXNlNjRTZWNyZXRGb3JKV1Q=
gametracker.app.jwtExpirationMs=86400000

gametracker.app.admin.enabled=true
gametracker.app.admin.username=admin
gametracker.app.admin.email=admin@gametracker.local
gametracker.app.admin.password=Admin123!